app_reservacion:
    resource: "@AppBundle/Controller/ReservacionController.php"
    type:     annotation

app_habitacion:
    resource: "@AppBundle/Controller/HabitacionController.php"
    type:     annotation

app_empleado:
    resource: "@AppBundle/Controller/EmpleadoController.php"
    type:     annotation

app_cliente:
    resource: "@AppBundle/Controller/ClienteController.php"
    type:     annotation

reservacion_login:
    path: login/
    defaults: {_controller: AppBundle:Reservacion:login}

reservacion_index:
    path: reservacion/
    defaults: {_controller: AppBundle:Reservacion:index}

reservacion_new:
    path: reservacion/new
    defaults: {_controller: AppBundle:Reservacion:new}
    
reservacion_show:
    path: reservacion/{id}
    defaults: {_controller: AppBundle:Reservacion:show}
    
reservacion_edit:
    path: reservacion/{id}/edit
    defaults: {_controller: AppBundle:Reservacion:edit}

reservacion_delete:
    path: reservacion/{id}/delete
    defaults: {_controller: AppBundle:Reservacion:delete}

empleado_index:
    path: empleado/
    defaults: {_controller: AppBundle:Empleado:index}

empleado_new:
    path: empleado/new
    defaults: {_controller: AppBundle:Empleado:new}
    
empleado_show:
    path: empleado/{id}
    defaults: {_controller: AppBundle:Empleado:show}
    
empleado_edit:
    path: empleado/{id}/edit
    defaults: {_controller: AppBundle:Empleado:edit}

empleado_delete:
    path: empleado/{id}/delete
    defaults: {_controller: AppBundle:Empleado:delete}

cliente_index:
    path: cliente/
    defaults: {_controller: AppBundle:Cliente:index}

cliente_new:
    path: cliente/new
    defaults: {_controller: AppBundle:Cliente:new}
    
cliente_show:
    path: cliente/{id}
    defaults: {_controller: AppBundle:Cliente:show}
    
cliente_edit:
    path: cliente/{id}/edit
    defaults: {_controller: AppBundle:Cliente:edit}

cliente_delete:
    path: cliente/{id}/delete
    defaults: {_controller: AppBundle:Cliente:delete}
 
habitacion_index:
    path: habitacion/
    defaults: {_controller: AppBundle:Habitacion:index}

habitacion_new:
    path: habitacion/new
    defaults: {_controller: AppBundle:Habitacion:new}
    
habitacion_show:
    path: habitacion/{id}
    defaults: {_controller: AppBundle:Habitacion:show}
    
habitacion_edit:
    path: habitacion/{id}/edit
    defaults: {_controller: AppBundle:Habitacion:edit}

habitacion_delete:
    path: habitacion/{id}/delete
    defaults: {_controller: AppBundle:Habitacion:delete}
                        
blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
